management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      enabled: true
      show-details: never
  metrics:
    enable:
      system: false
      process: false