dependencies {
  api project(":lib")
  testImplementation libs.delta.kernel.api
  testImplementation libs.delta.kernel.defaults
  testImplementation(libs.hadoop.common) {
    exclude group: 'org.slf4j', module: 'slf4j-reload4j'
  }
}

tasks.named('test') {
  useJUnitPlatform()
  testLogging.showStandardStreams = true
}